sed 's/$OFFSET/0/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/10000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/20000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/30000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/40000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/50000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/60000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/70000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/80000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/90000/' sim1_altrim_batch_template.sh | sbatch
