sed 's/$OFFSET/0/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/1000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/2000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/3000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/4000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/5000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/6000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/7000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/8000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/9000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/10000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/11000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/12000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/13000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/14000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/15000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/16000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/17000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/18000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/19000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/20000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/21000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/22000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/23000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/24000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/25000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/26000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/27000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/28000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/29000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/30000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/31000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/32000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/33000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/34000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/35000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/36000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/37000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/38000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/39000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/40000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/41000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/42000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/43000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/44000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/45000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/46000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/47000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/48000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/49000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/50000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/51000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/52000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/53000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/54000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/55000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/56000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/57000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/58000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/59000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/60000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/61000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/62000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/63000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/64000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/65000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/66000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/67000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/68000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/69000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/70000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/71000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/72000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/73000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/74000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/75000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/76000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/77000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/78000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/79000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/80000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/81000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/82000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/83000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/84000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/85000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/86000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/87000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/88000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/89000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/90000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/91000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/92000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/93000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/94000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/95000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/96000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/97000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/98000/' sim1_altrim_batch_template.sh | sbatch
sed 's/$OFFSET/99000/' sim1_altrim_batch_template.sh | sbatch
